spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/Security_QueryDSL?autoReconnect=true&useSSL=false&amp&serverTimezone=UTC
    username: root
    password: 1234