spring:
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect