spring:
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true